[I 11:54:27.431 LabApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 11:54:27.432 LabApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 11:54:27.560 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 11:54:28.048 LabApp] jupyter_tensorboard extension loaded.
[I 11:54:28.051 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.10/dist-packages/jupyterlab
[I 11:54:28.051 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 11:54:28.053 LabApp] [Jupytext Server Extension] NotebookApp.contents_manager_class is (a subclass of) jupytext.TextFileContentsManager already - OK
[I 11:54:28.056 LabApp] Serving notebooks from local directory: /workspace
[I 11:54:28.056 LabApp] Jupyter Notebook 6.4.10 is running at:
[I 11:54:28.056 LabApp] http://hostname:8888/
[I 11:54:28.056 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 11:54:36.646 LabApp] 302 GET /notebook/s-jain-training-21/streamserver/ (127.0.0.6) 0.410000ms
[W 11:54:37.532 LabApp] Could not determine jupyterlab build status without nodejs
[E 11:54:40.145 LabApp] Uncaught exception GET /notebook/s-jain-training-21/streamserver/lab/api/extensions?1745236477625 (127.0.0.6)
    HTTPServerRequest(protocol='http', host='192.168.1.248:32243', method='GET', uri='/notebook/s-jain-training-21/streamserver/lab/api/extensions?1745236477625', version='HTTP/1.1', remote_ip='127.0.0.6')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/usr/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
        future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 221, in get
        extensions = yield self.manager.list_extensions()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 91, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 160, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 191, in _load_outdated
        data = yield self.executor.submit(
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
      File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
        return self.__get_result()
      File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
        raise self._exception
      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/commands.py", line 542, in get_latest_compatible_package_versions
        return handler.latest_compatible_package_versions(names)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/commands.py", line 1680, in latest_compatible_package_versions
        ret = self._run([which('npm'), 'pack'] + keys, cwd=tempdir)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab_server/process.py", line 59, in which
        raise ValueError(msg)
    ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
[W 11:54:40.148 LabApp] Unhandled error
[E 11:54:40.148 LabApp] {
      "Host": "192.168.1.248:32243",
      "Accept": "*/*",
      "Referer": "http://192.168.1.248:32243/notebook/s-jain-training-21/streamserver/lab?",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0"
    }
[E 11:54:40.148 LabApp] 500 GET /notebook/s-jain-training-21/streamserver/lab/api/extensions?1745236477625 (127.0.0.6) 2092.500000ms referer=http://192.168.1.248:32243/notebook/s-jain-training-21/streamserver/lab?
[E 11:54:40.149 LabApp] Uncaught exception GET /notebook/s-jain-training-21/streamserver/lab/api/extensions?1745236478638 (127.0.0.6)
    HTTPServerRequest(protocol='http', host='192.168.1.248:32243', method='GET', uri='/notebook/s-jain-training-21/streamserver/lab/api/extensions?1745236478638', version='HTTP/1.1', remote_ip='127.0.0.6')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/usr/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
        future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 221, in get
        extensions = yield self.manager.list_extensions()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 91, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 160, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
    ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
[W 11:54:40.149 LabApp] Unhandled error
[E 11:54:40.149 LabApp] {
      "Host": "192.168.1.248:32243",
      "Accept": "*/*",
      "Referer": "http://192.168.1.248:32243/notebook/s-jain-training-21/streamserver/lab?",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0"
    }
[E 11:54:40.149 LabApp] 500 GET /notebook/s-jain-training-21/streamserver/lab/api/extensions?1745236478638 (127.0.0.6) 1527.470000ms referer=http://192.168.1.248:32243/notebook/s-jain-training-21/streamserver/lab?
[I 11:54:53.290 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
