[I 05:21:32.583 LabApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 05:21:32.584 LabApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 05:21:32.705 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 05:21:33.076 LabApp] jupyter_tensorboard extension loaded.
[I 05:21:33.078 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.10/dist-packages/jupyterlab
[I 05:21:33.078 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 05:21:33.080 LabApp] [Jupytext Server Extension] NotebookApp.contents_manager_class is (a subclass of) jupytext.TextFileContentsManager already - OK
[I 05:21:33.083 LabApp] Serving notebooks from local directory: /workspace
[I 05:21:33.083 LabApp] Jupyter Notebook 6.4.10 is running at:
[I 05:21:33.083 LabApp] http://hostname:8888/
[I 05:21:33.083 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 05:21:51.092 LabApp] 302 GET /notebook/kubeflow-deepops-example-com/testing/ (127.0.0.6) 0.390000ms
[W 05:21:51.752 LabApp] Could not determine jupyterlab build status without nodejs
[E 05:21:52.742 LabApp] Uncaught exception GET /notebook/kubeflow-deepops-example-com/testing/lab/api/extensions?1744780912348 (127.0.0.6)
    HTTPServerRequest(protocol='http', host='192.168.1.248:32243', method='GET', uri='/notebook/kubeflow-deepops-example-com/testing/lab/api/extensions?1744780912348', version='HTTP/1.1', remote_ip='127.0.0.6')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/usr/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
        future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 221, in get
        extensions = yield self.manager.list_extensions()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 91, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 160, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 191, in _load_outdated
        data = yield self.executor.submit(
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
      File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
        return self.__get_result()
      File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
        raise self._exception
      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/commands.py", line 542, in get_latest_compatible_package_versions
        return handler.latest_compatible_package_versions(names)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/commands.py", line 1680, in latest_compatible_package_versions
        ret = self._run([which('npm'), 'pack'] + keys, cwd=tempdir)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab_server/process.py", line 59, in which
        raise ValueError(msg)
    ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
[W 05:21:52.744 LabApp] Unhandled error
[E 05:21:52.744 LabApp] {
      "Host": "192.168.1.248:32243",
      "Accept": "*/*",
      "Referer": "http://192.168.1.248:32243/notebook/kubeflow-deepops-example-com/testing/lab?",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0"
    }
[E 05:21:52.744 LabApp] 500 GET /notebook/kubeflow-deepops-example-com/testing/lab/api/extensions?1744780912348 (127.0.0.6) 436.810000ms referer=http://192.168.1.248:32243/notebook/kubeflow-deepops-example-com/testing/lab?
[E 05:21:53.316 LabApp] Uncaught exception GET /notebook/kubeflow-deepops-example-com/testing/lab/api/extensions?1744780913349 (127.0.0.6)
    HTTPServerRequest(protocol='http', host='192.168.1.248:32243', method='GET', uri='/notebook/kubeflow-deepops-example-com/testing/lab/api/extensions?1744780913349', version='HTTP/1.1', remote_ip='127.0.0.6')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 221, in get
        extensions = yield self.manager.list_extensions()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 91, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
        yielded = self.gen.throw(exc)
      File "/usr/local/lib/python3.10/dist-packages/jupyterlab/handlers/extension_manager_handler.py", line 160, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
        value = future.result()
    ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
[W 05:21:53.317 LabApp] Unhandled error
[E 05:21:53.317 LabApp] {
      "Host": "192.168.1.248:32243",
      "Accept": "*/*",
      "Referer": "http://192.168.1.248:32243/notebook/kubeflow-deepops-example-com/testing/lab?",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0"
    }
[E 05:21:53.317 LabApp] 500 GET /notebook/kubeflow-deepops-example-com/testing/lab/api/extensions?1744780913349 (127.0.0.6) 8.920000ms referer=http://192.168.1.248:32243/notebook/kubeflow-deepops-example-com/testing/lab?
[I 05:21:54.622 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
[I 05:22:07.382 LabApp] Creating new notebook in 
[I 05:22:07.406 LabApp] Saving Untitled.ipynb
[I 05:22:07.406 LabApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[I 05:22:07.579 LabApp] Kernel started: 179e2ada-f5cf-4a15-b381-c86978955627, name: python3
[I 05:42:27.964 LabApp] Starting buffering for 179e2ada-f5cf-4a15-b381-c86978955627:6c83b404-de36-49b2-b66d-599b92aa6fd1
Websocket closed
